---
kind: pipeline
name: deploy-stg

steps:
  - name: tag
    image: golang
    commands:    
      - echo -n "latest,$DRONE_COMMIT" > .tags

  - name: image-create
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: harborteste.lab.vaultid.com.br
      repo: harborteste.lab.vaultid.com.br/teste/dronedemo
      username:
        from_secret: harbor_user
      password:
        from_secret: harbor_password
